"""Pydantic models for API requests and responses."""

from typing import Annotated, Literal

from pydantic import BaseModel, Field, StringConstraints, field_validator

# Thread IDs are UUIDs generated by POST /api/threads, but any URL-safe id
# (such as older ids already stored in the checkpoint DB) is accepted.
THREAD_ID_PATTERN = r"^[A-Za-z0-9_-]{1,128}$"
ThreadId = Annotated[str, StringConstraints(pattern=THREAD_ID_PATTERN)]


class ChatRequest(BaseModel):
    thread_id: ThreadId
    message: str = Field(max_length=20_000)

    @field_validator("message")
    @classmethod
    def message_not_blank(cls, value: str) -> str:
        value = value.strip()
        if not value:
            raise ValueError("Message must not be empty.")
        return value


class ResumeRequest(BaseModel):
    """Human decision for a graph paused by `interrupt()` (e.g. stock purchase)."""

    thread_id: ThreadId
    decision: Literal["yes", "no"]


class ThreadCreated(BaseModel):
    thread_id: str


class ThreadSummary(BaseModel):
    thread_id: str
    title: str
    updated_at: str | None = None


class ThreadList(BaseModel):
    threads: list[ThreadSummary]


class ToolCallInfo(BaseModel):
    # The model's tool-call id, so a stream that resumes a paused run can update this entry.
    id: str
    name: str
    # "pending" = the tool call never produced a result (e.g. awaiting approval)
    status: Literal["done", "error", "pending"]


class ChatMessage(BaseModel):
    role: Literal["user", "assistant"]
    content: str
    tools: list[ToolCallInfo] = []


class PendingInterrupt(BaseModel):
    message: str


class ThreadDetail(BaseModel):
    thread_id: str
    messages: list[ChatMessage]
    pending_interrupt: PendingInterrupt | None = None


class UploadResponse(BaseModel):
    filename: str
    message: str


class ErrorResponse(BaseModel):
    detail: str
